### ISSUE TITLE
the purpose of reversing y-axis reference_points?

### ISSUE THREAD

**Issue by zp5070** [yuantianyuan01/StreamMapNet#3]
Dear author:
       When I learn the map decoder, I notice that the y-axis of reference_points  are reversed 
before sending to ench decoder layer(in MapTransformer.py  Line 118) but I don't know the reason. Could you please tell me why this operation is needed?

**Comment by yuantianyuan01** [comment]
Hi, 

In the NuScenes coordinate system, the X-axis represents the forward direction, while the Y-axis represents the leftward direction. When we project this onto the Bird's Eye View (BEV) space, the X-axis points rightward and the Y-axis points upwards.  Consequently, the coordinates for the top-left corner in the BEV space are denoted as (0, 1), and the bottom-right corner as (1, 0). However, when querying BEV features using deformable attention, the reference points are expected to follow the typical image coordinate system where top-left is (0, 0) and bottom-right is (1, 1) (See more details [here](https://github.com/yuantianyuan01/StreamMapNet/blob/main/plugin/models/transformer_utils/CustomMSDeformableAttention.py#L162)) . That's why we need to reverse the Y-axis before entering the deformable attention.
